import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Contact from './components/Contact'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header></Header>
          <Contact></Contact>
        </header>
        {/* <main>{children}</main> */}
      </body>
    </html>
  )
}
